# Configuration file for MoreShulkerShells plugin
# You can set your own drop amounts here
# If you set a number that's more/less than the set maximum/minimum, plugin will automatically use the default value

# SHULKER SHELL DROP AMOUNT
# (Default = 3, Min = 1, Max = 10)
shulker_shell_drop_amount: 3

# Last updated for MoreShulkerShells v1.1.3
# Version 1.1.3 works for MC versions 1.21 - 1.21.7
# End of config file