name: MoreShulkerShells
version: '1.1.5'
main: me.minecraft.plugin.moreShulkerShells.MoreShulkerShells
api-version: '1.21'
authors: [ JustErikSK ]
description: Shulkers will drop more shulker shells
folia-supported: true